// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package interview

import (
	"Goffer/kitex_gen/base"
	"context"
	"fmt"
	"github.com/cloudwego/kitex/pkg/streaming"
)

type StartInterviewReq struct {
	UserId   string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	ResumeId string `thrift:"resume_id,2" frugal:"2,default,string" json:"resume_id"`
}

func NewStartInterviewReq() *StartInterviewReq {
	return &StartInterviewReq{}
}

func (p *StartInterviewReq) InitDefault() {
}

func (p *StartInterviewReq) GetUserId() (v string) {
	return p.UserId
}

func (p *StartInterviewReq) GetResumeId() (v string) {
	return p.ResumeId
}
func (p *StartInterviewReq) SetUserId(val string) {
	p.UserId = val
}
func (p *StartInterviewReq) SetResumeId(val string) {
	p.ResumeId = val
}

func (p *StartInterviewReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartInterviewReq(%+v)", *p)
}

var fieldIDToName_StartInterviewReq = map[int16]string{
	1: "user_id",
	2: "resume_id",
}

type StartInterviewResp struct {
	Resp          *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	SessionId     string         `thrift:"session_id,2" frugal:"2,default,string" json:"session_id"`
	OpeningRemark string         `thrift:"opening_remark,3" frugal:"3,default,string" json:"opening_remark"`
}

func NewStartInterviewResp() *StartInterviewResp {
	return &StartInterviewResp{}
}

func (p *StartInterviewResp) InitDefault() {
}

var StartInterviewResp_Resp_DEFAULT *base.Response

func (p *StartInterviewResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return StartInterviewResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *StartInterviewResp) GetSessionId() (v string) {
	return p.SessionId
}

func (p *StartInterviewResp) GetOpeningRemark() (v string) {
	return p.OpeningRemark
}
func (p *StartInterviewResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *StartInterviewResp) SetSessionId(val string) {
	p.SessionId = val
}
func (p *StartInterviewResp) SetOpeningRemark(val string) {
	p.OpeningRemark = val
}

func (p *StartInterviewResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *StartInterviewResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartInterviewResp(%+v)", *p)
}

var fieldIDToName_StartInterviewResp = map[int16]string{
	1: "resp",
	2: "session_id",
	3: "opening_remark",
}

type ChatReq struct {
	SessionId string `thrift:"session_id,1" frugal:"1,default,string" json:"session_id"`
	Message   string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewChatReq() *ChatReq {
	return &ChatReq{}
}

func (p *ChatReq) InitDefault() {
}

func (p *ChatReq) GetSessionId() (v string) {
	return p.SessionId
}

func (p *ChatReq) GetMessage() (v string) {
	return p.Message
}
func (p *ChatReq) SetSessionId(val string) {
	p.SessionId = val
}
func (p *ChatReq) SetMessage(val string) {
	p.Message = val
}

func (p *ChatReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatReq(%+v)", *p)
}

var fieldIDToName_ChatReq = map[int16]string{
	1: "session_id",
	2: "message",
}

type ChatResp struct {
	Chunk string `thrift:"chunk,1" frugal:"1,default,string" json:"chunk"`
}

func NewChatResp() *ChatResp {
	return &ChatResp{}
}

func (p *ChatResp) InitDefault() {
}

func (p *ChatResp) GetChunk() (v string) {
	return p.Chunk
}
func (p *ChatResp) SetChunk(val string) {
	p.Chunk = val
}

func (p *ChatResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatResp(%+v)", *p)
}

var fieldIDToName_ChatResp = map[int16]string{
	1: "chunk",
}

type ChatMessage struct {
	Role    string `thrift:"role,1" frugal:"1,default,string" json:"role"`
	Content string `thrift:"content,2" frugal:"2,default,string" json:"content"`
}

func NewChatMessage() *ChatMessage {
	return &ChatMessage{}
}

func (p *ChatMessage) InitDefault() {
}

func (p *ChatMessage) GetRole() (v string) {
	return p.Role
}

func (p *ChatMessage) GetContent() (v string) {
	return p.Content
}
func (p *ChatMessage) SetRole(val string) {
	p.Role = val
}
func (p *ChatMessage) SetContent(val string) {
	p.Content = val
}

func (p *ChatMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatMessage(%+v)", *p)
}

var fieldIDToName_ChatMessage = map[int16]string{
	1: "role",
	2: "content",
}

type GetChatContextReq struct {
	SessionId     string `thrift:"session_id,1" frugal:"1,default,string" json:"session_id"`
	LatestUserMsg string `thrift:"latest_user_msg,2" frugal:"2,default,string" json:"latest_user_msg"`
}

func NewGetChatContextReq() *GetChatContextReq {
	return &GetChatContextReq{}
}

func (p *GetChatContextReq) InitDefault() {
}

func (p *GetChatContextReq) GetSessionId() (v string) {
	return p.SessionId
}

func (p *GetChatContextReq) GetLatestUserMsg() (v string) {
	return p.LatestUserMsg
}
func (p *GetChatContextReq) SetSessionId(val string) {
	p.SessionId = val
}
func (p *GetChatContextReq) SetLatestUserMsg(val string) {
	p.LatestUserMsg = val
}

func (p *GetChatContextReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetChatContextReq(%+v)", *p)
}

var fieldIDToName_GetChatContextReq = map[int16]string{
	1: "session_id",
	2: "latest_user_msg",
}

type GetChatContextResp struct {
	Resp      *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	FsmState  string         `thrift:"fsm_state,2" frugal:"2,default,string" json:"fsm_state"`
	History   []*ChatMessage `thrift:"history,3" frugal:"3,default,list<ChatMessage>" json:"history"`
	RagChunks string         `thrift:"rag_chunks,4" frugal:"4,default,string" json:"rag_chunks"`
}

func NewGetChatContextResp() *GetChatContextResp {
	return &GetChatContextResp{}
}

func (p *GetChatContextResp) InitDefault() {
}

var GetChatContextResp_Resp_DEFAULT *base.Response

func (p *GetChatContextResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return GetChatContextResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *GetChatContextResp) GetFsmState() (v string) {
	return p.FsmState
}

func (p *GetChatContextResp) GetHistory() (v []*ChatMessage) {
	return p.History
}

func (p *GetChatContextResp) GetRagChunks() (v string) {
	return p.RagChunks
}
func (p *GetChatContextResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *GetChatContextResp) SetFsmState(val string) {
	p.FsmState = val
}
func (p *GetChatContextResp) SetHistory(val []*ChatMessage) {
	p.History = val
}
func (p *GetChatContextResp) SetRagChunks(val string) {
	p.RagChunks = val
}

func (p *GetChatContextResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *GetChatContextResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetChatContextResp(%+v)", *p)
}

var fieldIDToName_GetChatContextResp = map[int16]string{
	1: "resp",
	2: "fsm_state",
	3: "history",
	4: "rag_chunks",
}

type InterviewService interface {
	StartInterview(ctx context.Context, req *StartInterviewReq) (r *StartInterviewResp, err error)

	ChatStream(req *ChatReq, stream InterviewService_ChatStreamServer) (err error)

	GetChatContext(ctx context.Context, req *GetChatContextReq) (r *GetChatContextResp, err error)
}

type InterviewServiceStartInterviewArgs struct {
	Req *StartInterviewReq `thrift:"req,1" frugal:"1,default,StartInterviewReq" json:"req"`
}

func NewInterviewServiceStartInterviewArgs() *InterviewServiceStartInterviewArgs {
	return &InterviewServiceStartInterviewArgs{}
}

func (p *InterviewServiceStartInterviewArgs) InitDefault() {
}

var InterviewServiceStartInterviewArgs_Req_DEFAULT *StartInterviewReq

func (p *InterviewServiceStartInterviewArgs) GetReq() (v *StartInterviewReq) {
	if !p.IsSetReq() {
		return InterviewServiceStartInterviewArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceStartInterviewArgs) SetReq(val *StartInterviewReq) {
	p.Req = val
}

func (p *InterviewServiceStartInterviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceStartInterviewArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceStartInterviewArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceStartInterviewArgs = map[int16]string{
	1: "req",
}

type InterviewServiceStartInterviewResult struct {
	Success *StartInterviewResp `thrift:"success,0,optional" frugal:"0,optional,StartInterviewResp" json:"success,omitempty"`
}

func NewInterviewServiceStartInterviewResult() *InterviewServiceStartInterviewResult {
	return &InterviewServiceStartInterviewResult{}
}

func (p *InterviewServiceStartInterviewResult) InitDefault() {
}

var InterviewServiceStartInterviewResult_Success_DEFAULT *StartInterviewResp

func (p *InterviewServiceStartInterviewResult) GetSuccess() (v *StartInterviewResp) {
	if !p.IsSetSuccess() {
		return InterviewServiceStartInterviewResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceStartInterviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*StartInterviewResp)
}

func (p *InterviewServiceStartInterviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceStartInterviewResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceStartInterviewResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceStartInterviewResult = map[int16]string{
	0: "success",
}

type InterviewServiceChatStreamArgs struct {
	Req *ChatReq `thrift:"req,1" frugal:"1,default,ChatReq" json:"req"`
}

func NewInterviewServiceChatStreamArgs() *InterviewServiceChatStreamArgs {
	return &InterviewServiceChatStreamArgs{}
}

func (p *InterviewServiceChatStreamArgs) InitDefault() {
}

var InterviewServiceChatStreamArgs_Req_DEFAULT *ChatReq

func (p *InterviewServiceChatStreamArgs) GetReq() (v *ChatReq) {
	if !p.IsSetReq() {
		return InterviewServiceChatStreamArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceChatStreamArgs) SetReq(val *ChatReq) {
	p.Req = val
}

func (p *InterviewServiceChatStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceChatStreamArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceChatStreamArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceChatStreamArgs = map[int16]string{
	1: "req",
}

type InterviewServiceChatStreamResult struct {
	Success *ChatResp `thrift:"success,0,optional" frugal:"0,optional,ChatResp" json:"success,omitempty"`
}

func NewInterviewServiceChatStreamResult() *InterviewServiceChatStreamResult {
	return &InterviewServiceChatStreamResult{}
}

func (p *InterviewServiceChatStreamResult) InitDefault() {
}

var InterviewServiceChatStreamResult_Success_DEFAULT *ChatResp

func (p *InterviewServiceChatStreamResult) GetSuccess() (v *ChatResp) {
	if !p.IsSetSuccess() {
		return InterviewServiceChatStreamResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceChatStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChatResp)
}

func (p *InterviewServiceChatStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceChatStreamResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceChatStreamResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceChatStreamResult = map[int16]string{
	0: "success",
}

type InterviewService_ChatStreamServer interface {
	streaming.Stream

	Send(*ChatResp) error
}

type InterviewServiceGetChatContextArgs struct {
	Req *GetChatContextReq `thrift:"req,1" frugal:"1,default,GetChatContextReq" json:"req"`
}

func NewInterviewServiceGetChatContextArgs() *InterviewServiceGetChatContextArgs {
	return &InterviewServiceGetChatContextArgs{}
}

func (p *InterviewServiceGetChatContextArgs) InitDefault() {
}

var InterviewServiceGetChatContextArgs_Req_DEFAULT *GetChatContextReq

func (p *InterviewServiceGetChatContextArgs) GetReq() (v *GetChatContextReq) {
	if !p.IsSetReq() {
		return InterviewServiceGetChatContextArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *InterviewServiceGetChatContextArgs) SetReq(val *GetChatContextReq) {
	p.Req = val
}

func (p *InterviewServiceGetChatContextArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *InterviewServiceGetChatContextArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceGetChatContextArgs(%+v)", *p)
}

var fieldIDToName_InterviewServiceGetChatContextArgs = map[int16]string{
	1: "req",
}

type InterviewServiceGetChatContextResult struct {
	Success *GetChatContextResp `thrift:"success,0,optional" frugal:"0,optional,GetChatContextResp" json:"success,omitempty"`
}

func NewInterviewServiceGetChatContextResult() *InterviewServiceGetChatContextResult {
	return &InterviewServiceGetChatContextResult{}
}

func (p *InterviewServiceGetChatContextResult) InitDefault() {
}

var InterviewServiceGetChatContextResult_Success_DEFAULT *GetChatContextResp

func (p *InterviewServiceGetChatContextResult) GetSuccess() (v *GetChatContextResp) {
	if !p.IsSetSuccess() {
		return InterviewServiceGetChatContextResult_Success_DEFAULT
	}
	return p.Success
}
func (p *InterviewServiceGetChatContextResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetChatContextResp)
}

func (p *InterviewServiceGetChatContextResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *InterviewServiceGetChatContextResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InterviewServiceGetChatContextResult(%+v)", *p)
}

var fieldIDToName_InterviewServiceGetChatContextResult = map[int16]string{
	0: "success",
}
