// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package agent

import (
	"Goffer/kitex_gen/base"
	"context"
	"fmt"
	"github.com/cloudwego/kitex/pkg/streaming"
)

type Message struct {
	Role    string `thrift:"role,1" frugal:"1,default,string" json:"role"`
	Content string `thrift:"content,2" frugal:"2,default,string" json:"content"`
}

func NewMessage() *Message {
	return &Message{}
}

func (p *Message) InitDefault() {
}

func (p *Message) GetRole() (v string) {
	return p.Role
}

func (p *Message) GetContent() (v string) {
	return p.Content
}
func (p *Message) SetRole(val string) {
	p.Role = val
}
func (p *Message) SetContent(val string) {
	p.Content = val
}

func (p *Message) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message(%+v)", *p)
}

var fieldIDToName_Message = map[int16]string{
	1: "role",
	2: "content",
}

type ChatStreamReq struct {
	SessionId string     `thrift:"session_id,1" frugal:"1,default,string" json:"session_id"`
	UserId    string     `thrift:"user_id,2" frugal:"2,default,string" json:"user_id"`
	Message   string     `thrift:"message,3" frugal:"3,default,string" json:"message"`
	FsmState  string     `thrift:"fsm_state,4" frugal:"4,default,string" json:"fsm_state"`
	ResumeId  string     `thrift:"resume_id,5" frugal:"5,default,string" json:"resume_id"`
	History   []*Message `thrift:"history,6" frugal:"6,default,list<Message>" json:"history"`
}

func NewChatStreamReq() *ChatStreamReq {
	return &ChatStreamReq{}
}

func (p *ChatStreamReq) InitDefault() {
}

func (p *ChatStreamReq) GetSessionId() (v string) {
	return p.SessionId
}

func (p *ChatStreamReq) GetUserId() (v string) {
	return p.UserId
}

func (p *ChatStreamReq) GetMessage() (v string) {
	return p.Message
}

func (p *ChatStreamReq) GetFsmState() (v string) {
	return p.FsmState
}

func (p *ChatStreamReq) GetResumeId() (v string) {
	return p.ResumeId
}

func (p *ChatStreamReq) GetHistory() (v []*Message) {
	return p.History
}
func (p *ChatStreamReq) SetSessionId(val string) {
	p.SessionId = val
}
func (p *ChatStreamReq) SetUserId(val string) {
	p.UserId = val
}
func (p *ChatStreamReq) SetMessage(val string) {
	p.Message = val
}
func (p *ChatStreamReq) SetFsmState(val string) {
	p.FsmState = val
}
func (p *ChatStreamReq) SetResumeId(val string) {
	p.ResumeId = val
}
func (p *ChatStreamReq) SetHistory(val []*Message) {
	p.History = val
}

func (p *ChatStreamReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatStreamReq(%+v)", *p)
}

var fieldIDToName_ChatStreamReq = map[int16]string{
	1: "session_id",
	2: "user_id",
	3: "message",
	4: "fsm_state",
	5: "resume_id",
	6: "history",
}

type ChatStreamResp struct {
	Chunk string `thrift:"chunk,1" frugal:"1,default,string" json:"chunk"`
}

func NewChatStreamResp() *ChatStreamResp {
	return &ChatStreamResp{}
}

func (p *ChatStreamResp) InitDefault() {
}

func (p *ChatStreamResp) GetChunk() (v string) {
	return p.Chunk
}
func (p *ChatStreamResp) SetChunk(val string) {
	p.Chunk = val
}

func (p *ChatStreamResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatStreamResp(%+v)", *p)
}

var fieldIDToName_ChatStreamResp = map[int16]string{
	1: "chunk",
}

type RetrieveReq struct {
	UserId     string   `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	Collection string   `thrift:"collection,2,required" frugal:"2,required,string" json:"collection"`
	Query      string   `thrift:"query,3,required" frugal:"3,required,string" json:"query"`
	TopK       *int32   `thrift:"top_k,4,optional" frugal:"4,optional,i32" json:"top_k,omitempty"`
	ResumeId   *string  `thrift:"resume_id,5,optional" frugal:"5,optional,string" json:"resume_id,omitempty"`
	Difficulty *string  `thrift:"difficulty,6,optional" frugal:"6,optional,string" json:"difficulty,omitempty"`
	Tags       []string `thrift:"tags,7,optional" frugal:"7,optional,list<string>" json:"tags,omitempty"`
	Company    *string  `thrift:"company,8,optional" frugal:"8,optional,string" json:"company,omitempty"`
}

func NewRetrieveReq() *RetrieveReq {
	return &RetrieveReq{}
}

func (p *RetrieveReq) InitDefault() {
}

func (p *RetrieveReq) GetUserId() (v string) {
	return p.UserId
}

func (p *RetrieveReq) GetCollection() (v string) {
	return p.Collection
}

func (p *RetrieveReq) GetQuery() (v string) {
	return p.Query
}

var RetrieveReq_TopK_DEFAULT int32

func (p *RetrieveReq) GetTopK() (v int32) {
	if !p.IsSetTopK() {
		return RetrieveReq_TopK_DEFAULT
	}
	return *p.TopK
}

var RetrieveReq_ResumeId_DEFAULT string

func (p *RetrieveReq) GetResumeId() (v string) {
	if !p.IsSetResumeId() {
		return RetrieveReq_ResumeId_DEFAULT
	}
	return *p.ResumeId
}

var RetrieveReq_Difficulty_DEFAULT string

func (p *RetrieveReq) GetDifficulty() (v string) {
	if !p.IsSetDifficulty() {
		return RetrieveReq_Difficulty_DEFAULT
	}
	return *p.Difficulty
}

var RetrieveReq_Tags_DEFAULT []string

func (p *RetrieveReq) GetTags() (v []string) {
	if !p.IsSetTags() {
		return RetrieveReq_Tags_DEFAULT
	}
	return p.Tags
}

var RetrieveReq_Company_DEFAULT string

func (p *RetrieveReq) GetCompany() (v string) {
	if !p.IsSetCompany() {
		return RetrieveReq_Company_DEFAULT
	}
	return *p.Company
}
func (p *RetrieveReq) SetUserId(val string) {
	p.UserId = val
}
func (p *RetrieveReq) SetCollection(val string) {
	p.Collection = val
}
func (p *RetrieveReq) SetQuery(val string) {
	p.Query = val
}
func (p *RetrieveReq) SetTopK(val *int32) {
	p.TopK = val
}
func (p *RetrieveReq) SetResumeId(val *string) {
	p.ResumeId = val
}
func (p *RetrieveReq) SetDifficulty(val *string) {
	p.Difficulty = val
}
func (p *RetrieveReq) SetTags(val []string) {
	p.Tags = val
}
func (p *RetrieveReq) SetCompany(val *string) {
	p.Company = val
}

func (p *RetrieveReq) IsSetTopK() bool {
	return p.TopK != nil
}

func (p *RetrieveReq) IsSetResumeId() bool {
	return p.ResumeId != nil
}

func (p *RetrieveReq) IsSetDifficulty() bool {
	return p.Difficulty != nil
}

func (p *RetrieveReq) IsSetTags() bool {
	return p.Tags != nil
}

func (p *RetrieveReq) IsSetCompany() bool {
	return p.Company != nil
}

func (p *RetrieveReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RetrieveReq(%+v)", *p)
}

var fieldIDToName_RetrieveReq = map[int16]string{
	1: "user_id",
	2: "collection",
	3: "query",
	4: "top_k",
	5: "resume_id",
	6: "difficulty",
	7: "tags",
	8: "company",
}

type RetrieveResp struct {
	Contexts []string       `thrift:"contexts,1" frugal:"1,default,list<string>" json:"contexts"`
	Resp     *base.Response `thrift:"resp,2" frugal:"2,default,base.Response" json:"resp"`
}

func NewRetrieveResp() *RetrieveResp {
	return &RetrieveResp{}
}

func (p *RetrieveResp) InitDefault() {
}

func (p *RetrieveResp) GetContexts() (v []string) {
	return p.Contexts
}

var RetrieveResp_Resp_DEFAULT *base.Response

func (p *RetrieveResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return RetrieveResp_Resp_DEFAULT
	}
	return p.Resp
}
func (p *RetrieveResp) SetContexts(val []string) {
	p.Contexts = val
}
func (p *RetrieveResp) SetResp(val *base.Response) {
	p.Resp = val
}

func (p *RetrieveResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *RetrieveResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RetrieveResp(%+v)", *p)
}

var fieldIDToName_RetrieveResp = map[int16]string{
	1: "contexts",
	2: "resp",
}

type AgentService interface {
	ChatStream(req *ChatStreamReq, stream AgentService_ChatStreamServer) (err error)

	RetrieveContext(ctx context.Context, req *RetrieveReq) (r *RetrieveResp, err error)
}

type AgentServiceChatStreamArgs struct {
	Req *ChatStreamReq `thrift:"req,1" frugal:"1,default,ChatStreamReq" json:"req"`
}

func NewAgentServiceChatStreamArgs() *AgentServiceChatStreamArgs {
	return &AgentServiceChatStreamArgs{}
}

func (p *AgentServiceChatStreamArgs) InitDefault() {
}

var AgentServiceChatStreamArgs_Req_DEFAULT *ChatStreamReq

func (p *AgentServiceChatStreamArgs) GetReq() (v *ChatStreamReq) {
	if !p.IsSetReq() {
		return AgentServiceChatStreamArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AgentServiceChatStreamArgs) SetReq(val *ChatStreamReq) {
	p.Req = val
}

func (p *AgentServiceChatStreamArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AgentServiceChatStreamArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentServiceChatStreamArgs(%+v)", *p)
}

var fieldIDToName_AgentServiceChatStreamArgs = map[int16]string{
	1: "req",
}

type AgentServiceChatStreamResult struct {
	Success *ChatStreamResp `thrift:"success,0,optional" frugal:"0,optional,ChatStreamResp" json:"success,omitempty"`
}

func NewAgentServiceChatStreamResult() *AgentServiceChatStreamResult {
	return &AgentServiceChatStreamResult{}
}

func (p *AgentServiceChatStreamResult) InitDefault() {
}

var AgentServiceChatStreamResult_Success_DEFAULT *ChatStreamResp

func (p *AgentServiceChatStreamResult) GetSuccess() (v *ChatStreamResp) {
	if !p.IsSetSuccess() {
		return AgentServiceChatStreamResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AgentServiceChatStreamResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChatStreamResp)
}

func (p *AgentServiceChatStreamResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AgentServiceChatStreamResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentServiceChatStreamResult(%+v)", *p)
}

var fieldIDToName_AgentServiceChatStreamResult = map[int16]string{
	0: "success",
}

type AgentService_ChatStreamServer interface {
	streaming.Stream

	Send(*ChatStreamResp) error
}

type AgentServiceRetrieveContextArgs struct {
	Req *RetrieveReq `thrift:"req,1" frugal:"1,default,RetrieveReq" json:"req"`
}

func NewAgentServiceRetrieveContextArgs() *AgentServiceRetrieveContextArgs {
	return &AgentServiceRetrieveContextArgs{}
}

func (p *AgentServiceRetrieveContextArgs) InitDefault() {
}

var AgentServiceRetrieveContextArgs_Req_DEFAULT *RetrieveReq

func (p *AgentServiceRetrieveContextArgs) GetReq() (v *RetrieveReq) {
	if !p.IsSetReq() {
		return AgentServiceRetrieveContextArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AgentServiceRetrieveContextArgs) SetReq(val *RetrieveReq) {
	p.Req = val
}

func (p *AgentServiceRetrieveContextArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AgentServiceRetrieveContextArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentServiceRetrieveContextArgs(%+v)", *p)
}

var fieldIDToName_AgentServiceRetrieveContextArgs = map[int16]string{
	1: "req",
}

type AgentServiceRetrieveContextResult struct {
	Success *RetrieveResp `thrift:"success,0,optional" frugal:"0,optional,RetrieveResp" json:"success,omitempty"`
}

func NewAgentServiceRetrieveContextResult() *AgentServiceRetrieveContextResult {
	return &AgentServiceRetrieveContextResult{}
}

func (p *AgentServiceRetrieveContextResult) InitDefault() {
}

var AgentServiceRetrieveContextResult_Success_DEFAULT *RetrieveResp

func (p *AgentServiceRetrieveContextResult) GetSuccess() (v *RetrieveResp) {
	if !p.IsSetSuccess() {
		return AgentServiceRetrieveContextResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AgentServiceRetrieveContextResult) SetSuccess(x interface{}) {
	p.Success = x.(*RetrieveResp)
}

func (p *AgentServiceRetrieveContextResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AgentServiceRetrieveContextResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentServiceRetrieveContextResult(%+v)", *p)
}

var fieldIDToName_AgentServiceRetrieveContextResult = map[int16]string{
	0: "success",
}
