// Code generated by Kitex v0.16.1. DO NOT EDIT.

package knowledgeservice

import (
	knowledge "Goffer/kitex_gen/knowledge"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"IngestQuestion": kitex.NewMethodInfo(
		ingestQuestionHandler,
		newKnowledgeServiceIngestQuestionArgs,
		newKnowledgeServiceIngestQuestionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadQuestion": kitex.NewMethodInfo(
		uploadQuestionHandler,
		newKnowledgeServiceUploadQuestionArgs,
		newKnowledgeServiceUploadQuestionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IngestJD": kitex.NewMethodInfo(
		ingestJDHandler,
		newKnowledgeServiceIngestJDArgs,
		newKnowledgeServiceIngestJDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadJD": kitex.NewMethodInfo(
		uploadJDHandler,
		newKnowledgeServiceUploadJDArgs,
		newKnowledgeServiceUploadJDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	knowledgeServiceServiceInfo                = NewServiceInfo()
	knowledgeServiceServiceInfoForClient       = NewServiceInfoForClient()
	knowledgeServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return knowledgeServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "KnowledgeService"
	handlerType := (*knowledge.KnowledgeService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "knowledge",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func ingestQuestionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceIngestQuestionArgs)
	realResult := result.(*knowledge.KnowledgeServiceIngestQuestionResult)
	success, err := handler.(knowledge.KnowledgeService).IngestQuestion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceIngestQuestionArgs() interface{} {
	return knowledge.NewKnowledgeServiceIngestQuestionArgs()
}

func newKnowledgeServiceIngestQuestionResult() interface{} {
	return knowledge.NewKnowledgeServiceIngestQuestionResult()
}

func uploadQuestionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceUploadQuestionArgs)
	realResult := result.(*knowledge.KnowledgeServiceUploadQuestionResult)
	success, err := handler.(knowledge.KnowledgeService).UploadQuestion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceUploadQuestionArgs() interface{} {
	return knowledge.NewKnowledgeServiceUploadQuestionArgs()
}

func newKnowledgeServiceUploadQuestionResult() interface{} {
	return knowledge.NewKnowledgeServiceUploadQuestionResult()
}

func ingestJDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceIngestJDArgs)
	realResult := result.(*knowledge.KnowledgeServiceIngestJDResult)
	success, err := handler.(knowledge.KnowledgeService).IngestJD(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceIngestJDArgs() interface{} {
	return knowledge.NewKnowledgeServiceIngestJDArgs()
}

func newKnowledgeServiceIngestJDResult() interface{} {
	return knowledge.NewKnowledgeServiceIngestJDResult()
}

func uploadJDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*knowledge.KnowledgeServiceUploadJDArgs)
	realResult := result.(*knowledge.KnowledgeServiceUploadJDResult)
	success, err := handler.(knowledge.KnowledgeService).UploadJD(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newKnowledgeServiceUploadJDArgs() interface{} {
	return knowledge.NewKnowledgeServiceUploadJDArgs()
}

func newKnowledgeServiceUploadJDResult() interface{} {
	return knowledge.NewKnowledgeServiceUploadJDResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) IngestQuestion(ctx context.Context, req *knowledge.IngestQuestionReq) (r *knowledge.IngestQuestionResp, err error) {
	var _args knowledge.KnowledgeServiceIngestQuestionArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceIngestQuestionResult
	if err = p.c.Call(ctx, "IngestQuestion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadQuestion(ctx context.Context, req *knowledge.UploadQuestionReq) (r *knowledge.UploadQuestionResp, err error) {
	var _args knowledge.KnowledgeServiceUploadQuestionArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceUploadQuestionResult
	if err = p.c.Call(ctx, "UploadQuestion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IngestJD(ctx context.Context, req *knowledge.IngestJDReq) (r *knowledge.IngestJDResp, err error) {
	var _args knowledge.KnowledgeServiceIngestJDArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceIngestJDResult
	if err = p.c.Call(ctx, "IngestJD", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadJD(ctx context.Context, req *knowledge.UploadJDReq) (r *knowledge.UploadJDResp, err error) {
	var _args knowledge.KnowledgeServiceUploadJDArgs
	_args.Req = req
	var _result knowledge.KnowledgeServiceUploadJDResult
	if err = p.c.Call(ctx, "UploadJD", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
