// Code generated by Kitex v0.16.1. DO NOT EDIT.

package agentservice

import (
	agent "Goffer/kitex_gen/agent"
	"context"
	"errors"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ChatStream": kitex.NewMethodInfo(
		chatStreamHandler,
		newAgentServiceChatStreamArgs,
		newAgentServiceChatStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"RetrieveContext": kitex.NewMethodInfo(
		retrieveContextHandler,
		newAgentServiceRetrieveContextArgs,
		newAgentServiceRetrieveContextResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	agentServiceServiceInfo                = NewServiceInfo()
	agentServiceServiceInfoForClient       = NewServiceInfoForClient()
	agentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return agentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return agentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return agentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AgentService"
	handlerType := (*agent.AgentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "agent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func chatStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, ok := arg.(*streaming.Args)
	if !ok {
		return errors.New("AgentService.ChatStream is a thrift streaming method, please call with Kitex StreamClient")
	}
	stream := &agentServiceChatStreamServer{st.Stream}
	req := new(agent.ChatStreamReq)
	if err := st.Stream.RecvMsg(req); err != nil {
		return err
	}
	return handler.(agent.AgentService).ChatStream(req, stream)
}

type agentServiceChatStreamClient struct {
	streaming.Stream
}

func (x *agentServiceChatStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *agentServiceChatStreamClient) Recv() (*agent.ChatStreamResp, error) {
	m := new(agent.ChatStreamResp)
	return m, x.Stream.RecvMsg(m)
}

type agentServiceChatStreamServer struct {
	streaming.Stream
}

func (x *agentServiceChatStreamServer) Send(m *agent.ChatStreamResp) error {
	return x.Stream.SendMsg(m)
}

func newAgentServiceChatStreamArgs() interface{} {
	return agent.NewAgentServiceChatStreamArgs()
}

func newAgentServiceChatStreamResult() interface{} {
	return agent.NewAgentServiceChatStreamResult()
}

func retrieveContextHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*agent.AgentServiceRetrieveContextArgs)
	realResult := result.(*agent.AgentServiceRetrieveContextResult)
	success, err := handler.(agent.AgentService).RetrieveContext(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAgentServiceRetrieveContextArgs() interface{} {
	return agent.NewAgentServiceRetrieveContextArgs()
}

func newAgentServiceRetrieveContextResult() interface{} {
	return agent.NewAgentServiceRetrieveContextResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ChatStream(ctx context.Context, req *agent.ChatStreamReq) (AgentService_ChatStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "ChatStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &agentServiceChatStreamClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) RetrieveContext(ctx context.Context, req *agent.RetrieveReq) (r *agent.RetrieveResp, err error) {
	var _args agent.AgentServiceRetrieveContextArgs
	_args.Req = req
	var _result agent.AgentServiceRetrieveContextResult
	if err = p.c.Call(ctx, "RetrieveContext", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
