// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package base

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type InterviewStatus int64

const (
	InterviewStatus_IDLE          InterviewStatus = 0
	InterviewStatus_SELF_INTRO    InterviewStatus = 1
	InterviewStatus_PROJECT_QUERY InterviewStatus = 2
	InterviewStatus_TECH_ASK      InterviewStatus = 3
	InterviewStatus_ENDING        InterviewStatus = 4
)

func (p InterviewStatus) String() string {
	switch p {
	case InterviewStatus_IDLE:
		return "IDLE"
	case InterviewStatus_SELF_INTRO:
		return "SELF_INTRO"
	case InterviewStatus_PROJECT_QUERY:
		return "PROJECT_QUERY"
	case InterviewStatus_TECH_ASK:
		return "TECH_ASK"
	case InterviewStatus_ENDING:
		return "ENDING"
	}
	return "<UNSET>"
}

func InterviewStatusFromString(s string) (InterviewStatus, error) {
	switch s {
	case "IDLE":
		return InterviewStatus_IDLE, nil
	case "SELF_INTRO":
		return InterviewStatus_SELF_INTRO, nil
	case "PROJECT_QUERY":
		return InterviewStatus_PROJECT_QUERY, nil
	case "TECH_ASK":
		return InterviewStatus_TECH_ASK, nil
	case "ENDING":
		return InterviewStatus_ENDING, nil
	}
	return InterviewStatus(0), fmt.Errorf("not a valid InterviewStatus string")
}

func InterviewStatusPtr(v InterviewStatus) *InterviewStatus { return &v }
func (p *InterviewStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = InterviewStatus(result.Int64)
	return
}

func (p *InterviewStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Response struct {
	Code    int64  `thrift:"code,1" frugal:"1,default,i64" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewResponse() *Response {
	return &Response{}
}

func (p *Response) InitDefault() {
}

func (p *Response) GetCode() (v int64) {
	return p.Code
}

func (p *Response) GetMessage() (v string) {
	return p.Message
}
func (p *Response) SetCode(val int64) {
	p.Code = val
}
func (p *Response) SetMessage(val string) {
	p.Message = val
}

func (p *Response) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Response(%+v)", *p)
}

var fieldIDToName_Response = map[int16]string{
	1: "code",
	2: "message",
}
