// Code generated by Kitex v0.16.1. DO NOT EDIT.

package interviewservice

import (
	interview "Goffer/kitex_gen/interview"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	StartInterview(ctx context.Context, req *interview.StartInterviewReq, callOptions ...callopt.Option) (r *interview.StartInterviewResp, err error)
	GetChatContext(ctx context.Context, req *interview.GetChatContextReq, callOptions ...callopt.Option) (r *interview.GetChatContextResp, err error)
	SaveChatRecord(ctx context.Context, req *interview.SaveChatRecordReq, callOptions ...callopt.Option) (r *interview.SaveChatRecordResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kInterviewServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInterviewServiceClient struct {
	*kClient
}

func (p *kInterviewServiceClient) StartInterview(ctx context.Context, req *interview.StartInterviewReq, callOptions ...callopt.Option) (r *interview.StartInterviewResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartInterview(ctx, req)
}

func (p *kInterviewServiceClient) GetChatContext(ctx context.Context, req *interview.GetChatContextReq, callOptions ...callopt.Option) (r *interview.GetChatContextResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetChatContext(ctx, req)
}

func (p *kInterviewServiceClient) SaveChatRecord(ctx context.Context, req *interview.SaveChatRecordReq, callOptions ...callopt.Option) (r *interview.SaveChatRecordResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveChatRecord(ctx, req)
}
