// Code generated by Kitex v0.16.1. DO NOT EDIT.

package interviewservice

import (
	interview "Goffer/kitex_gen/interview"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"StartInterview": kitex.NewMethodInfo(
		startInterviewHandler,
		newInterviewServiceStartInterviewArgs,
		newInterviewServiceStartInterviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetChatContext": kitex.NewMethodInfo(
		getChatContextHandler,
		newInterviewServiceGetChatContextArgs,
		newInterviewServiceGetChatContextResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SaveChatRecord": kitex.NewMethodInfo(
		saveChatRecordHandler,
		newInterviewServiceSaveChatRecordArgs,
		newInterviewServiceSaveChatRecordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	interviewServiceServiceInfo                = NewServiceInfo()
	interviewServiceServiceInfoForClient       = NewServiceInfoForClient()
	interviewServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return interviewServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return interviewServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return interviewServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InterviewService"
	handlerType := (*interview.InterviewService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "interview",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func startInterviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interview.InterviewServiceStartInterviewArgs)
	realResult := result.(*interview.InterviewServiceStartInterviewResult)
	success, err := handler.(interview.InterviewService).StartInterview(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInterviewServiceStartInterviewArgs() interface{} {
	return interview.NewInterviewServiceStartInterviewArgs()
}

func newInterviewServiceStartInterviewResult() interface{} {
	return interview.NewInterviewServiceStartInterviewResult()
}

func getChatContextHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interview.InterviewServiceGetChatContextArgs)
	realResult := result.(*interview.InterviewServiceGetChatContextResult)
	success, err := handler.(interview.InterviewService).GetChatContext(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInterviewServiceGetChatContextArgs() interface{} {
	return interview.NewInterviewServiceGetChatContextArgs()
}

func newInterviewServiceGetChatContextResult() interface{} {
	return interview.NewInterviewServiceGetChatContextResult()
}

func saveChatRecordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interview.InterviewServiceSaveChatRecordArgs)
	realResult := result.(*interview.InterviewServiceSaveChatRecordResult)
	success, err := handler.(interview.InterviewService).SaveChatRecord(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInterviewServiceSaveChatRecordArgs() interface{} {
	return interview.NewInterviewServiceSaveChatRecordArgs()
}

func newInterviewServiceSaveChatRecordResult() interface{} {
	return interview.NewInterviewServiceSaveChatRecordResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) StartInterview(ctx context.Context, req *interview.StartInterviewReq) (r *interview.StartInterviewResp, err error) {
	var _args interview.InterviewServiceStartInterviewArgs
	_args.Req = req
	var _result interview.InterviewServiceStartInterviewResult
	if err = p.c.Call(ctx, "StartInterview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetChatContext(ctx context.Context, req *interview.GetChatContextReq) (r *interview.GetChatContextResp, err error) {
	var _args interview.InterviewServiceGetChatContextArgs
	_args.Req = req
	var _result interview.InterviewServiceGetChatContextResult
	if err = p.c.Call(ctx, "GetChatContext", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SaveChatRecord(ctx context.Context, req *interview.SaveChatRecordReq) (r *interview.SaveChatRecordResp, err error) {
	var _args interview.InterviewServiceSaveChatRecordArgs
	_args.Req = req
	var _result interview.InterviewServiceSaveChatRecordResult
	if err = p.c.Call(ctx, "SaveChatRecord", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
