// Code generated by Kitex v0.16.1. DO NOT EDIT.

package interviewservice

import (
	interview "Goffer/kitex_gen/interview"
	"context"
	"errors"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"StartInterview": kitex.NewMethodInfo(
		startInterviewHandler,
		newInterviewServiceStartInterviewArgs,
		newInterviewServiceStartInterviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChatStream": kitex.NewMethodInfo(
		chatStreamHandler,
		newInterviewServiceChatStreamArgs,
		newInterviewServiceChatStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"GetChatContext": kitex.NewMethodInfo(
		getChatContextHandler,
		newInterviewServiceGetChatContextArgs,
		newInterviewServiceGetChatContextResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	interviewServiceServiceInfo                = NewServiceInfo()
	interviewServiceServiceInfoForClient       = NewServiceInfoForClient()
	interviewServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return interviewServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return interviewServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return interviewServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InterviewService"
	handlerType := (*interview.InterviewService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "interview",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func startInterviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interview.InterviewServiceStartInterviewArgs)
	realResult := result.(*interview.InterviewServiceStartInterviewResult)
	success, err := handler.(interview.InterviewService).StartInterview(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInterviewServiceStartInterviewArgs() interface{} {
	return interview.NewInterviewServiceStartInterviewArgs()
}

func newInterviewServiceStartInterviewResult() interface{} {
	return interview.NewInterviewServiceStartInterviewResult()
}

func chatStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, ok := arg.(*streaming.Args)
	if !ok {
		return errors.New("InterviewService.ChatStream is a thrift streaming method, please call with Kitex StreamClient")
	}
	stream := &interviewServiceChatStreamServer{st.Stream}
	req := new(interview.ChatReq)
	if err := st.Stream.RecvMsg(req); err != nil {
		return err
	}
	return handler.(interview.InterviewService).ChatStream(req, stream)
}

type interviewServiceChatStreamClient struct {
	streaming.Stream
}

func (x *interviewServiceChatStreamClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *interviewServiceChatStreamClient) Recv() (*interview.ChatResp, error) {
	m := new(interview.ChatResp)
	return m, x.Stream.RecvMsg(m)
}

type interviewServiceChatStreamServer struct {
	streaming.Stream
}

func (x *interviewServiceChatStreamServer) Send(m *interview.ChatResp) error {
	return x.Stream.SendMsg(m)
}

func newInterviewServiceChatStreamArgs() interface{} {
	return interview.NewInterviewServiceChatStreamArgs()
}

func newInterviewServiceChatStreamResult() interface{} {
	return interview.NewInterviewServiceChatStreamResult()
}

func getChatContextHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interview.InterviewServiceGetChatContextArgs)
	realResult := result.(*interview.InterviewServiceGetChatContextResult)
	success, err := handler.(interview.InterviewService).GetChatContext(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInterviewServiceGetChatContextArgs() interface{} {
	return interview.NewInterviewServiceGetChatContextArgs()
}

func newInterviewServiceGetChatContextResult() interface{} {
	return interview.NewInterviewServiceGetChatContextResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) StartInterview(ctx context.Context, req *interview.StartInterviewReq) (r *interview.StartInterviewResp, err error) {
	var _args interview.InterviewServiceStartInterviewArgs
	_args.Req = req
	var _result interview.InterviewServiceStartInterviewResult
	if err = p.c.Call(ctx, "StartInterview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChatStream(ctx context.Context, req *interview.ChatReq) (InterviewService_ChatStreamClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "ChatStream", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &interviewServiceChatStreamClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) GetChatContext(ctx context.Context, req *interview.GetChatContextReq) (r *interview.GetChatContextResp, err error) {
	var _args interview.InterviewServiceGetChatContextArgs
	_args.Req = req
	var _result interview.InterviewServiceGetChatContextResult
	if err = p.c.Call(ctx, "GetChatContext", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
