// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package knowledge

import (
	"Goffer/kitex_gen/base"
	"context"
	"fmt"
)

type Question struct {
	QuestionId      string   `thrift:"question_id,1" frugal:"1,default,string" json:"question_id"`
	QuestionContent string   `thrift:"question_content,2" frugal:"2,default,string" json:"question_content"`
	StandardAnswer  string   `thrift:"standard_answer,3" frugal:"3,default,string" json:"standard_answer"`
	Tags            []string `thrift:"tags,4" frugal:"4,default,list<string>" json:"tags"`
	Difficulty      string   `thrift:"difficulty,5" frugal:"5,default,string" json:"difficulty"`
	CreateTime      string   `thrift:"create_time,6" frugal:"6,default,string" json:"create_time"`
}

func NewQuestion() *Question {
	return &Question{}
}

func (p *Question) InitDefault() {
}

func (p *Question) GetQuestionId() (v string) {
	return p.QuestionId
}

func (p *Question) GetQuestionContent() (v string) {
	return p.QuestionContent
}

func (p *Question) GetStandardAnswer() (v string) {
	return p.StandardAnswer
}

func (p *Question) GetTags() (v []string) {
	return p.Tags
}

func (p *Question) GetDifficulty() (v string) {
	return p.Difficulty
}

func (p *Question) GetCreateTime() (v string) {
	return p.CreateTime
}
func (p *Question) SetQuestionId(val string) {
	p.QuestionId = val
}
func (p *Question) SetQuestionContent(val string) {
	p.QuestionContent = val
}
func (p *Question) SetStandardAnswer(val string) {
	p.StandardAnswer = val
}
func (p *Question) SetTags(val []string) {
	p.Tags = val
}
func (p *Question) SetDifficulty(val string) {
	p.Difficulty = val
}
func (p *Question) SetCreateTime(val string) {
	p.CreateTime = val
}

func (p *Question) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Question(%+v)", *p)
}

var fieldIDToName_Question = map[int16]string{
	1: "question_id",
	2: "question_content",
	3: "standard_answer",
	4: "tags",
	5: "difficulty",
	6: "create_time",
}

type JobDescription struct {
	JdId             string   `thrift:"jd_id,1" frugal:"1,default,string" json:"jd_id"`
	Title            string   `thrift:"title,2" frugal:"2,default,string" json:"title"`
	Company          string   `thrift:"company,3" frugal:"3,default,string" json:"company"`
	Responsibilities string   `thrift:"responsibilities,4" frugal:"4,default,string" json:"responsibilities"`
	Requirements     string   `thrift:"requirements,5" frugal:"5,default,string" json:"requirements"`
	Tags             []string `thrift:"tags,6" frugal:"6,default,list<string>" json:"tags"`
	CreateTime       string   `thrift:"create_time,7" frugal:"7,default,string" json:"create_time"`
}

func NewJobDescription() *JobDescription {
	return &JobDescription{}
}

func (p *JobDescription) InitDefault() {
}

func (p *JobDescription) GetJdId() (v string) {
	return p.JdId
}

func (p *JobDescription) GetTitle() (v string) {
	return p.Title
}

func (p *JobDescription) GetCompany() (v string) {
	return p.Company
}

func (p *JobDescription) GetResponsibilities() (v string) {
	return p.Responsibilities
}

func (p *JobDescription) GetRequirements() (v string) {
	return p.Requirements
}

func (p *JobDescription) GetTags() (v []string) {
	return p.Tags
}

func (p *JobDescription) GetCreateTime() (v string) {
	return p.CreateTime
}
func (p *JobDescription) SetJdId(val string) {
	p.JdId = val
}
func (p *JobDescription) SetTitle(val string) {
	p.Title = val
}
func (p *JobDescription) SetCompany(val string) {
	p.Company = val
}
func (p *JobDescription) SetResponsibilities(val string) {
	p.Responsibilities = val
}
func (p *JobDescription) SetRequirements(val string) {
	p.Requirements = val
}
func (p *JobDescription) SetTags(val []string) {
	p.Tags = val
}
func (p *JobDescription) SetCreateTime(val string) {
	p.CreateTime = val
}

func (p *JobDescription) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JobDescription(%+v)", *p)
}

var fieldIDToName_JobDescription = map[int16]string{
	1: "jd_id",
	2: "title",
	3: "company",
	4: "responsibilities",
	5: "requirements",
	6: "tags",
	7: "create_time",
}

type IngestQuestionReq struct {
	QuestionContent string   `thrift:"question_content,1,required" frugal:"1,required,string" json:"question_content"`
	StandardAnswer  string   `thrift:"standard_answer,2,required" frugal:"2,required,string" json:"standard_answer"`
	Tags            []string `thrift:"tags,3,optional" frugal:"3,optional,list<string>" json:"tags,omitempty"`
	Difficulty      *string  `thrift:"difficulty,4,optional" frugal:"4,optional,string" json:"difficulty,omitempty"`
}

func NewIngestQuestionReq() *IngestQuestionReq {
	return &IngestQuestionReq{}
}

func (p *IngestQuestionReq) InitDefault() {
}

func (p *IngestQuestionReq) GetQuestionContent() (v string) {
	return p.QuestionContent
}

func (p *IngestQuestionReq) GetStandardAnswer() (v string) {
	return p.StandardAnswer
}

var IngestQuestionReq_Tags_DEFAULT []string

func (p *IngestQuestionReq) GetTags() (v []string) {
	if !p.IsSetTags() {
		return IngestQuestionReq_Tags_DEFAULT
	}
	return p.Tags
}

var IngestQuestionReq_Difficulty_DEFAULT string

func (p *IngestQuestionReq) GetDifficulty() (v string) {
	if !p.IsSetDifficulty() {
		return IngestQuestionReq_Difficulty_DEFAULT
	}
	return *p.Difficulty
}
func (p *IngestQuestionReq) SetQuestionContent(val string) {
	p.QuestionContent = val
}
func (p *IngestQuestionReq) SetStandardAnswer(val string) {
	p.StandardAnswer = val
}
func (p *IngestQuestionReq) SetTags(val []string) {
	p.Tags = val
}
func (p *IngestQuestionReq) SetDifficulty(val *string) {
	p.Difficulty = val
}

func (p *IngestQuestionReq) IsSetTags() bool {
	return p.Tags != nil
}

func (p *IngestQuestionReq) IsSetDifficulty() bool {
	return p.Difficulty != nil
}

func (p *IngestQuestionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IngestQuestionReq(%+v)", *p)
}

var fieldIDToName_IngestQuestionReq = map[int16]string{
	1: "question_content",
	2: "standard_answer",
	3: "tags",
	4: "difficulty",
}

type IngestQuestionResp struct {
	Resp       *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	QuestionId string         `thrift:"question_id,2" frugal:"2,default,string" json:"question_id"`
}

func NewIngestQuestionResp() *IngestQuestionResp {
	return &IngestQuestionResp{}
}

func (p *IngestQuestionResp) InitDefault() {
}

var IngestQuestionResp_Resp_DEFAULT *base.Response

func (p *IngestQuestionResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return IngestQuestionResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *IngestQuestionResp) GetQuestionId() (v string) {
	return p.QuestionId
}
func (p *IngestQuestionResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *IngestQuestionResp) SetQuestionId(val string) {
	p.QuestionId = val
}

func (p *IngestQuestionResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *IngestQuestionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IngestQuestionResp(%+v)", *p)
}

var fieldIDToName_IngestQuestionResp = map[int16]string{
	1: "resp",
	2: "question_id",
}

type UploadQuestionReq struct {
	UserId      string `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	FileName    string `thrift:"file_name,2,required" frugal:"2,required,string" json:"file_name"`
	FileContent []byte `thrift:"file_content,3,required" frugal:"3,required,binary" json:"file_content"`
	ContentType string `thrift:"content_type,4,required" frugal:"4,required,string" json:"content_type"`
}

func NewUploadQuestionReq() *UploadQuestionReq {
	return &UploadQuestionReq{}
}

func (p *UploadQuestionReq) InitDefault() {
}

func (p *UploadQuestionReq) GetUserId() (v string) {
	return p.UserId
}

func (p *UploadQuestionReq) GetFileName() (v string) {
	return p.FileName
}

func (p *UploadQuestionReq) GetFileContent() (v []byte) {
	return p.FileContent
}

func (p *UploadQuestionReq) GetContentType() (v string) {
	return p.ContentType
}
func (p *UploadQuestionReq) SetUserId(val string) {
	p.UserId = val
}
func (p *UploadQuestionReq) SetFileName(val string) {
	p.FileName = val
}
func (p *UploadQuestionReq) SetFileContent(val []byte) {
	p.FileContent = val
}
func (p *UploadQuestionReq) SetContentType(val string) {
	p.ContentType = val
}

func (p *UploadQuestionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadQuestionReq(%+v)", *p)
}

var fieldIDToName_UploadQuestionReq = map[int16]string{
	1: "user_id",
	2: "file_name",
	3: "file_content",
	4: "content_type",
}

type UploadQuestionResp struct {
	Resp    *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	TaskId  string         `thrift:"task_id,2" frugal:"2,default,string" json:"task_id"`
	FileUrl string         `thrift:"file_url,3" frugal:"3,default,string" json:"file_url"`
}

func NewUploadQuestionResp() *UploadQuestionResp {
	return &UploadQuestionResp{}
}

func (p *UploadQuestionResp) InitDefault() {
}

var UploadQuestionResp_Resp_DEFAULT *base.Response

func (p *UploadQuestionResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return UploadQuestionResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *UploadQuestionResp) GetTaskId() (v string) {
	return p.TaskId
}

func (p *UploadQuestionResp) GetFileUrl() (v string) {
	return p.FileUrl
}
func (p *UploadQuestionResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *UploadQuestionResp) SetTaskId(val string) {
	p.TaskId = val
}
func (p *UploadQuestionResp) SetFileUrl(val string) {
	p.FileUrl = val
}

func (p *UploadQuestionResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *UploadQuestionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadQuestionResp(%+v)", *p)
}

var fieldIDToName_UploadQuestionResp = map[int16]string{
	1: "resp",
	2: "task_id",
	3: "file_url",
}

type IngestJDReq struct {
	Company          string   `thrift:"company,1,required" frugal:"1,required,string" json:"company"`
	Title            string   `thrift:"title,2,required" frugal:"2,required,string" json:"title"`
	Responsibilities string   `thrift:"responsibilities,3,required" frugal:"3,required,string" json:"responsibilities"`
	Requirements     string   `thrift:"requirements,4,required" frugal:"4,required,string" json:"requirements"`
	Tags             []string `thrift:"tags,5,optional" frugal:"5,optional,list<string>" json:"tags,omitempty"`
}

func NewIngestJDReq() *IngestJDReq {
	return &IngestJDReq{}
}

func (p *IngestJDReq) InitDefault() {
}

func (p *IngestJDReq) GetCompany() (v string) {
	return p.Company
}

func (p *IngestJDReq) GetTitle() (v string) {
	return p.Title
}

func (p *IngestJDReq) GetResponsibilities() (v string) {
	return p.Responsibilities
}

func (p *IngestJDReq) GetRequirements() (v string) {
	return p.Requirements
}

var IngestJDReq_Tags_DEFAULT []string

func (p *IngestJDReq) GetTags() (v []string) {
	if !p.IsSetTags() {
		return IngestJDReq_Tags_DEFAULT
	}
	return p.Tags
}
func (p *IngestJDReq) SetCompany(val string) {
	p.Company = val
}
func (p *IngestJDReq) SetTitle(val string) {
	p.Title = val
}
func (p *IngestJDReq) SetResponsibilities(val string) {
	p.Responsibilities = val
}
func (p *IngestJDReq) SetRequirements(val string) {
	p.Requirements = val
}
func (p *IngestJDReq) SetTags(val []string) {
	p.Tags = val
}

func (p *IngestJDReq) IsSetTags() bool {
	return p.Tags != nil
}

func (p *IngestJDReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IngestJDReq(%+v)", *p)
}

var fieldIDToName_IngestJDReq = map[int16]string{
	1: "company",
	2: "title",
	3: "responsibilities",
	4: "requirements",
	5: "tags",
}

type IngestJDResp struct {
	Resp *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	JdId string         `thrift:"jd_id,2" frugal:"2,default,string" json:"jd_id"`
}

func NewIngestJDResp() *IngestJDResp {
	return &IngestJDResp{}
}

func (p *IngestJDResp) InitDefault() {
}

var IngestJDResp_Resp_DEFAULT *base.Response

func (p *IngestJDResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return IngestJDResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *IngestJDResp) GetJdId() (v string) {
	return p.JdId
}
func (p *IngestJDResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *IngestJDResp) SetJdId(val string) {
	p.JdId = val
}

func (p *IngestJDResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *IngestJDResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("IngestJDResp(%+v)", *p)
}

var fieldIDToName_IngestJDResp = map[int16]string{
	1: "resp",
	2: "jd_id",
}

type UploadJDReq struct {
	UserId      string `thrift:"user_id,1,required" frugal:"1,required,string" json:"user_id"`
	FileName    string `thrift:"file_name,2,required" frugal:"2,required,string" json:"file_name"`
	FileContent []byte `thrift:"file_content,3,required" frugal:"3,required,binary" json:"file_content"`
	ContentType string `thrift:"content_type,4,required" frugal:"4,required,string" json:"content_type"`
}

func NewUploadJDReq() *UploadJDReq {
	return &UploadJDReq{}
}

func (p *UploadJDReq) InitDefault() {
}

func (p *UploadJDReq) GetUserId() (v string) {
	return p.UserId
}

func (p *UploadJDReq) GetFileName() (v string) {
	return p.FileName
}

func (p *UploadJDReq) GetFileContent() (v []byte) {
	return p.FileContent
}

func (p *UploadJDReq) GetContentType() (v string) {
	return p.ContentType
}
func (p *UploadJDReq) SetUserId(val string) {
	p.UserId = val
}
func (p *UploadJDReq) SetFileName(val string) {
	p.FileName = val
}
func (p *UploadJDReq) SetFileContent(val []byte) {
	p.FileContent = val
}
func (p *UploadJDReq) SetContentType(val string) {
	p.ContentType = val
}

func (p *UploadJDReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadJDReq(%+v)", *p)
}

var fieldIDToName_UploadJDReq = map[int16]string{
	1: "user_id",
	2: "file_name",
	3: "file_content",
	4: "content_type",
}

type UploadJDResp struct {
	Resp    *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	TaskId  string         `thrift:"task_id,2" frugal:"2,default,string" json:"task_id"`
	FileUrl string         `thrift:"file_url,3" frugal:"3,default,string" json:"file_url"`
}

func NewUploadJDResp() *UploadJDResp {
	return &UploadJDResp{}
}

func (p *UploadJDResp) InitDefault() {
}

var UploadJDResp_Resp_DEFAULT *base.Response

func (p *UploadJDResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return UploadJDResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *UploadJDResp) GetTaskId() (v string) {
	return p.TaskId
}

func (p *UploadJDResp) GetFileUrl() (v string) {
	return p.FileUrl
}
func (p *UploadJDResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *UploadJDResp) SetTaskId(val string) {
	p.TaskId = val
}
func (p *UploadJDResp) SetFileUrl(val string) {
	p.FileUrl = val
}

func (p *UploadJDResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *UploadJDResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadJDResp(%+v)", *p)
}

var fieldIDToName_UploadJDResp = map[int16]string{
	1: "resp",
	2: "task_id",
	3: "file_url",
}

type KnowledgeService interface {
	IngestQuestion(ctx context.Context, req *IngestQuestionReq) (r *IngestQuestionResp, err error)

	UploadQuestion(ctx context.Context, req *UploadQuestionReq) (r *UploadQuestionResp, err error)

	IngestJD(ctx context.Context, req *IngestJDReq) (r *IngestJDResp, err error)

	UploadJD(ctx context.Context, req *UploadJDReq) (r *UploadJDResp, err error)
}

type KnowledgeServiceIngestQuestionArgs struct {
	Req *IngestQuestionReq `thrift:"req,1" frugal:"1,default,IngestQuestionReq" json:"req"`
}

func NewKnowledgeServiceIngestQuestionArgs() *KnowledgeServiceIngestQuestionArgs {
	return &KnowledgeServiceIngestQuestionArgs{}
}

func (p *KnowledgeServiceIngestQuestionArgs) InitDefault() {
}

var KnowledgeServiceIngestQuestionArgs_Req_DEFAULT *IngestQuestionReq

func (p *KnowledgeServiceIngestQuestionArgs) GetReq() (v *IngestQuestionReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceIngestQuestionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceIngestQuestionArgs) SetReq(val *IngestQuestionReq) {
	p.Req = val
}

func (p *KnowledgeServiceIngestQuestionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceIngestQuestionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceIngestQuestionArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceIngestQuestionArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceIngestQuestionResult struct {
	Success *IngestQuestionResp `thrift:"success,0,optional" frugal:"0,optional,IngestQuestionResp" json:"success,omitempty"`
}

func NewKnowledgeServiceIngestQuestionResult() *KnowledgeServiceIngestQuestionResult {
	return &KnowledgeServiceIngestQuestionResult{}
}

func (p *KnowledgeServiceIngestQuestionResult) InitDefault() {
}

var KnowledgeServiceIngestQuestionResult_Success_DEFAULT *IngestQuestionResp

func (p *KnowledgeServiceIngestQuestionResult) GetSuccess() (v *IngestQuestionResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceIngestQuestionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceIngestQuestionResult) SetSuccess(x interface{}) {
	p.Success = x.(*IngestQuestionResp)
}

func (p *KnowledgeServiceIngestQuestionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceIngestQuestionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceIngestQuestionResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceIngestQuestionResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceUploadQuestionArgs struct {
	Req *UploadQuestionReq `thrift:"req,1" frugal:"1,default,UploadQuestionReq" json:"req"`
}

func NewKnowledgeServiceUploadQuestionArgs() *KnowledgeServiceUploadQuestionArgs {
	return &KnowledgeServiceUploadQuestionArgs{}
}

func (p *KnowledgeServiceUploadQuestionArgs) InitDefault() {
}

var KnowledgeServiceUploadQuestionArgs_Req_DEFAULT *UploadQuestionReq

func (p *KnowledgeServiceUploadQuestionArgs) GetReq() (v *UploadQuestionReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceUploadQuestionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceUploadQuestionArgs) SetReq(val *UploadQuestionReq) {
	p.Req = val
}

func (p *KnowledgeServiceUploadQuestionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceUploadQuestionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceUploadQuestionArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceUploadQuestionArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceUploadQuestionResult struct {
	Success *UploadQuestionResp `thrift:"success,0,optional" frugal:"0,optional,UploadQuestionResp" json:"success,omitempty"`
}

func NewKnowledgeServiceUploadQuestionResult() *KnowledgeServiceUploadQuestionResult {
	return &KnowledgeServiceUploadQuestionResult{}
}

func (p *KnowledgeServiceUploadQuestionResult) InitDefault() {
}

var KnowledgeServiceUploadQuestionResult_Success_DEFAULT *UploadQuestionResp

func (p *KnowledgeServiceUploadQuestionResult) GetSuccess() (v *UploadQuestionResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceUploadQuestionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceUploadQuestionResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadQuestionResp)
}

func (p *KnowledgeServiceUploadQuestionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceUploadQuestionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceUploadQuestionResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceUploadQuestionResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceIngestJDArgs struct {
	Req *IngestJDReq `thrift:"req,1" frugal:"1,default,IngestJDReq" json:"req"`
}

func NewKnowledgeServiceIngestJDArgs() *KnowledgeServiceIngestJDArgs {
	return &KnowledgeServiceIngestJDArgs{}
}

func (p *KnowledgeServiceIngestJDArgs) InitDefault() {
}

var KnowledgeServiceIngestJDArgs_Req_DEFAULT *IngestJDReq

func (p *KnowledgeServiceIngestJDArgs) GetReq() (v *IngestJDReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceIngestJDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceIngestJDArgs) SetReq(val *IngestJDReq) {
	p.Req = val
}

func (p *KnowledgeServiceIngestJDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceIngestJDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceIngestJDArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceIngestJDArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceIngestJDResult struct {
	Success *IngestJDResp `thrift:"success,0,optional" frugal:"0,optional,IngestJDResp" json:"success,omitempty"`
}

func NewKnowledgeServiceIngestJDResult() *KnowledgeServiceIngestJDResult {
	return &KnowledgeServiceIngestJDResult{}
}

func (p *KnowledgeServiceIngestJDResult) InitDefault() {
}

var KnowledgeServiceIngestJDResult_Success_DEFAULT *IngestJDResp

func (p *KnowledgeServiceIngestJDResult) GetSuccess() (v *IngestJDResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceIngestJDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceIngestJDResult) SetSuccess(x interface{}) {
	p.Success = x.(*IngestJDResp)
}

func (p *KnowledgeServiceIngestJDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceIngestJDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceIngestJDResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceIngestJDResult = map[int16]string{
	0: "success",
}

type KnowledgeServiceUploadJDArgs struct {
	Req *UploadJDReq `thrift:"req,1" frugal:"1,default,UploadJDReq" json:"req"`
}

func NewKnowledgeServiceUploadJDArgs() *KnowledgeServiceUploadJDArgs {
	return &KnowledgeServiceUploadJDArgs{}
}

func (p *KnowledgeServiceUploadJDArgs) InitDefault() {
}

var KnowledgeServiceUploadJDArgs_Req_DEFAULT *UploadJDReq

func (p *KnowledgeServiceUploadJDArgs) GetReq() (v *UploadJDReq) {
	if !p.IsSetReq() {
		return KnowledgeServiceUploadJDArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *KnowledgeServiceUploadJDArgs) SetReq(val *UploadJDReq) {
	p.Req = val
}

func (p *KnowledgeServiceUploadJDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *KnowledgeServiceUploadJDArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceUploadJDArgs(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceUploadJDArgs = map[int16]string{
	1: "req",
}

type KnowledgeServiceUploadJDResult struct {
	Success *UploadJDResp `thrift:"success,0,optional" frugal:"0,optional,UploadJDResp" json:"success,omitempty"`
}

func NewKnowledgeServiceUploadJDResult() *KnowledgeServiceUploadJDResult {
	return &KnowledgeServiceUploadJDResult{}
}

func (p *KnowledgeServiceUploadJDResult) InitDefault() {
}

var KnowledgeServiceUploadJDResult_Success_DEFAULT *UploadJDResp

func (p *KnowledgeServiceUploadJDResult) GetSuccess() (v *UploadJDResp) {
	if !p.IsSetSuccess() {
		return KnowledgeServiceUploadJDResult_Success_DEFAULT
	}
	return p.Success
}
func (p *KnowledgeServiceUploadJDResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadJDResp)
}

func (p *KnowledgeServiceUploadJDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *KnowledgeServiceUploadJDResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("KnowledgeServiceUploadJDResult(%+v)", *p)
}

var fieldIDToName_KnowledgeServiceUploadJDResult = map[int16]string{
	0: "success",
}
