app:
  env: dev

jwt:
  issuer: "goffer_interview_api"
  secret_key: "your_very_secure_secret_key_here_make_it_long_and_random"
  expiration_time: "24h"

server:
  port: 8888

etcd:
  address: "localhost:2379"
service:
  name: "goffer_rpc_user"

db:
  user: "root"
  password: "123456"
  host: "localhost"
  port: 3306
  name: "goffer_user"

redis:
  host: "localhost"
  port: 6379
  password: "123456"
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  topic: "resume_parse_topic"

qdrant:
  host: "localhost"
  port: 6334
  api_key: "root"

volc_engine:
  # 火山引擎 (豆包大模型) 配置
  key: "f978d5ef-2be0-4d29-84b3-8103d12bdd68"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  chat_model_id: "ep-20260502211927-7zfck"
  embed_model_id: "ep-20260502211508-tjhqp"
  vision_model_id: "ep-20260502210446-ghx6c"

minio:
  endpoint: "localhost:9000"
  public_url: "http://localhost:9000"
  access_key: "admin"
  secret_key: "password123"
  # 【修改】原本存笔记图片，现在改为存用户上传的简历 PDF 或面试录音
  bucket: "goffer-resumes"
  use_ssl: false

trace:
  jaeger_endpoint: "http://localhost:14268/api/traces"