app:
  env: dev

server:
  # Hertz 网关对外暴露的端口
  port: 8080

jwt:
  # 面试项目的签发者
  issuer: "goffer_interview_api"
  secret_key: "your_very_secure_secret_key_here_make_it_long_and_random"
  expiration_time: "24h"

trace:
  # Jaeger 链路追踪地址
  jaeger_endpoint: "http://localhost:14268/api/traces"

etcd:
  # Etcd 注册中心的地址
  address: "localhost:2379"

rpc_clients:
  user:
    name: "goffer.rpc.user"       # User 服务的独有名称
    rpc_timeout: 3000             # 毫秒，也就是 3 秒
    conn_timeout: 50              # 毫秒
  interview:
    name: "goffer.rpc.interview"  # Interview 服务的独有名称
    rpc_timeout: 5000             # AI 面试可能耗时更长，配置 5 秒
    conn_timeout: 50

redis:
  host: "localhost"
  port: 6379
  password: "123456"
  db: 0

volc_engine:
  # 火山引擎 (豆包大模型) 配置
  key: "f978d5ef-2be0-4d29-84b3-8103d12bdd68"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  chat_model_id: "ep-20260502211927-7zfck"
  embed_model_id: "ep-20260502211508-tjhqp"
  vision_model_id: "ep-20260502210446-ghx6c"