// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"Goffer/kitex_gen/base"
	"context"
	"fmt"
)

type RegisterReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetUsername() (v string) {
	return p.Username
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterReq) SetUsername(val string) {
	p.Username = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "username",
	2: "password",
}

type RegisterResp struct {
	Resp *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{}
}

func (p *RegisterResp) InitDefault() {
}

var RegisterResp_Resp_DEFAULT *base.Response

func (p *RegisterResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return RegisterResp_Resp_DEFAULT
	}
	return p.Resp
}
func (p *RegisterResp) SetResp(val *base.Response) {
	p.Resp = val
}

func (p *RegisterResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "resp",
}

type LoginReq struct {
	Username string `thrift:"username,1" frugal:"1,default,string" json:"username"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetUsername() (v string) {
	return p.Username
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}
func (p *LoginReq) SetUsername(val string) {
	p.Username = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "username",
	2: "password",
}

type LoginResp struct {
	Resp  *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	Token string         `thrift:"token,2" frugal:"2,default,string" json:"token"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

var LoginResp_Resp_DEFAULT *base.Response

func (p *LoginResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return LoginResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *LoginResp) GetToken() (v string) {
	return p.Token
}
func (p *LoginResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *LoginResp) SetToken(val string) {
	p.Token = val
}

func (p *LoginResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "resp",
	2: "token",
}

type UploadResumeReq struct {
	UserId      string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	FileName    string `thrift:"file_name,2" frugal:"2,default,string" json:"file_name"`
	FileContent []byte `thrift:"file_content,3" frugal:"3,default,binary" json:"file_content"`
	ContentType string `thrift:"content_type,4" frugal:"4,default,string" json:"content_type"`
}

func NewUploadResumeReq() *UploadResumeReq {
	return &UploadResumeReq{}
}

func (p *UploadResumeReq) InitDefault() {
}

func (p *UploadResumeReq) GetUserId() (v string) {
	return p.UserId
}

func (p *UploadResumeReq) GetFileName() (v string) {
	return p.FileName
}

func (p *UploadResumeReq) GetFileContent() (v []byte) {
	return p.FileContent
}

func (p *UploadResumeReq) GetContentType() (v string) {
	return p.ContentType
}
func (p *UploadResumeReq) SetUserId(val string) {
	p.UserId = val
}
func (p *UploadResumeReq) SetFileName(val string) {
	p.FileName = val
}
func (p *UploadResumeReq) SetFileContent(val []byte) {
	p.FileContent = val
}
func (p *UploadResumeReq) SetContentType(val string) {
	p.ContentType = val
}

func (p *UploadResumeReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadResumeReq(%+v)", *p)
}

var fieldIDToName_UploadResumeReq = map[int16]string{
	1: "user_id",
	2: "file_name",
	3: "file_content",
	4: "content_type",
}

type UploadResumeResp struct {
	Resp     *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	ResumeId string         `thrift:"resume_id,2" frugal:"2,default,string" json:"resume_id"`
	FileUrl  string         `thrift:"file_url,3" frugal:"3,default,string" json:"file_url"`
}

func NewUploadResumeResp() *UploadResumeResp {
	return &UploadResumeResp{}
}

func (p *UploadResumeResp) InitDefault() {
}

var UploadResumeResp_Resp_DEFAULT *base.Response

func (p *UploadResumeResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return UploadResumeResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *UploadResumeResp) GetResumeId() (v string) {
	return p.ResumeId
}

func (p *UploadResumeResp) GetFileUrl() (v string) {
	return p.FileUrl
}
func (p *UploadResumeResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *UploadResumeResp) SetResumeId(val string) {
	p.ResumeId = val
}
func (p *UploadResumeResp) SetFileUrl(val string) {
	p.FileUrl = val
}

func (p *UploadResumeResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *UploadResumeResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadResumeResp(%+v)", *p)
}

var fieldIDToName_UploadResumeResp = map[int16]string{
	1: "resp",
	2: "resume_id",
	3: "file_url",
}

type CheckResumeStatusReq struct {
	UserId   string `thrift:"user_id,1" frugal:"1,default,string" json:"user_id"`
	ResumeId string `thrift:"resume_id,2" frugal:"2,default,string" json:"resume_id"`
}

func NewCheckResumeStatusReq() *CheckResumeStatusReq {
	return &CheckResumeStatusReq{}
}

func (p *CheckResumeStatusReq) InitDefault() {
}

func (p *CheckResumeStatusReq) GetUserId() (v string) {
	return p.UserId
}

func (p *CheckResumeStatusReq) GetResumeId() (v string) {
	return p.ResumeId
}
func (p *CheckResumeStatusReq) SetUserId(val string) {
	p.UserId = val
}
func (p *CheckResumeStatusReq) SetResumeId(val string) {
	p.ResumeId = val
}

func (p *CheckResumeStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckResumeStatusReq(%+v)", *p)
}

var fieldIDToName_CheckResumeStatusReq = map[int16]string{
	1: "user_id",
	2: "resume_id",
}

type CheckResumeStatusResp struct {
	Resp        *base.Response `thrift:"resp,1" frugal:"1,default,base.Response" json:"resp"`
	ParseStatus int32          `thrift:"parse_status,2" frugal:"2,default,i32" json:"parse_status"`
}

func NewCheckResumeStatusResp() *CheckResumeStatusResp {
	return &CheckResumeStatusResp{}
}

func (p *CheckResumeStatusResp) InitDefault() {
}

var CheckResumeStatusResp_Resp_DEFAULT *base.Response

func (p *CheckResumeStatusResp) GetResp() (v *base.Response) {
	if !p.IsSetResp() {
		return CheckResumeStatusResp_Resp_DEFAULT
	}
	return p.Resp
}

func (p *CheckResumeStatusResp) GetParseStatus() (v int32) {
	return p.ParseStatus
}
func (p *CheckResumeStatusResp) SetResp(val *base.Response) {
	p.Resp = val
}
func (p *CheckResumeStatusResp) SetParseStatus(val int32) {
	p.ParseStatus = val
}

func (p *CheckResumeStatusResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *CheckResumeStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckResumeStatusResp(%+v)", *p)
}

var fieldIDToName_CheckResumeStatusResp = map[int16]string{
	1: "resp",
	2: "parse_status",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	UploadResume(ctx context.Context, req *UploadResumeReq) (r *UploadResumeResp, err error)

	CheckResumeStatus(ctx context.Context, req *CheckResumeStatusReq) (r *CheckResumeStatusResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceUploadResumeArgs struct {
	Req *UploadResumeReq `thrift:"req,1" frugal:"1,default,UploadResumeReq" json:"req"`
}

func NewUserServiceUploadResumeArgs() *UserServiceUploadResumeArgs {
	return &UserServiceUploadResumeArgs{}
}

func (p *UserServiceUploadResumeArgs) InitDefault() {
}

var UserServiceUploadResumeArgs_Req_DEFAULT *UploadResumeReq

func (p *UserServiceUploadResumeArgs) GetReq() (v *UploadResumeReq) {
	if !p.IsSetReq() {
		return UserServiceUploadResumeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUploadResumeArgs) SetReq(val *UploadResumeReq) {
	p.Req = val
}

func (p *UserServiceUploadResumeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUploadResumeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUploadResumeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUploadResumeArgs = map[int16]string{
	1: "req",
}

type UserServiceUploadResumeResult struct {
	Success *UploadResumeResp `thrift:"success,0,optional" frugal:"0,optional,UploadResumeResp" json:"success,omitempty"`
}

func NewUserServiceUploadResumeResult() *UserServiceUploadResumeResult {
	return &UserServiceUploadResumeResult{}
}

func (p *UserServiceUploadResumeResult) InitDefault() {
}

var UserServiceUploadResumeResult_Success_DEFAULT *UploadResumeResp

func (p *UserServiceUploadResumeResult) GetSuccess() (v *UploadResumeResp) {
	if !p.IsSetSuccess() {
		return UserServiceUploadResumeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUploadResumeResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadResumeResp)
}

func (p *UserServiceUploadResumeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUploadResumeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUploadResumeResult(%+v)", *p)
}

var fieldIDToName_UserServiceUploadResumeResult = map[int16]string{
	0: "success",
}

type UserServiceCheckResumeStatusArgs struct {
	Req *CheckResumeStatusReq `thrift:"req,1" frugal:"1,default,CheckResumeStatusReq" json:"req"`
}

func NewUserServiceCheckResumeStatusArgs() *UserServiceCheckResumeStatusArgs {
	return &UserServiceCheckResumeStatusArgs{}
}

func (p *UserServiceCheckResumeStatusArgs) InitDefault() {
}

var UserServiceCheckResumeStatusArgs_Req_DEFAULT *CheckResumeStatusReq

func (p *UserServiceCheckResumeStatusArgs) GetReq() (v *CheckResumeStatusReq) {
	if !p.IsSetReq() {
		return UserServiceCheckResumeStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCheckResumeStatusArgs) SetReq(val *CheckResumeStatusReq) {
	p.Req = val
}

func (p *UserServiceCheckResumeStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCheckResumeStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCheckResumeStatusArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCheckResumeStatusArgs = map[int16]string{
	1: "req",
}

type UserServiceCheckResumeStatusResult struct {
	Success *CheckResumeStatusResp `thrift:"success,0,optional" frugal:"0,optional,CheckResumeStatusResp" json:"success,omitempty"`
}

func NewUserServiceCheckResumeStatusResult() *UserServiceCheckResumeStatusResult {
	return &UserServiceCheckResumeStatusResult{}
}

func (p *UserServiceCheckResumeStatusResult) InitDefault() {
}

var UserServiceCheckResumeStatusResult_Success_DEFAULT *CheckResumeStatusResp

func (p *UserServiceCheckResumeStatusResult) GetSuccess() (v *CheckResumeStatusResp) {
	if !p.IsSetSuccess() {
		return UserServiceCheckResumeStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCheckResumeStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckResumeStatusResp)
}

func (p *UserServiceCheckResumeStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCheckResumeStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCheckResumeStatusResult(%+v)", *p)
}

var fieldIDToName_UserServiceCheckResumeStatusResult = map[int16]string{
	0: "success",
}
